language: java
jdk:
  - openjdk17 # Java version
  before_deploy:
    - rvm install 3.0.4
    - rvm --default use 3.0.4
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "pedidos-springboot"
before_install:
  - chmod +x mvnw